
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 悦动族

on:
  workflow_dispatch:
  schedule:
    - cron: '0,30 15-16 * * *' # UTC时间 +8 北京
  watch:
    types: started
  repository_dispatch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/zsy822143265/dkd2.git ~/dkd2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          cd ~/dkd2
          git checkout main
          npm install
      - name: '运行 【悦动族】'
        run: |
          cd ~/dkd2/Task
          node yuedongzu.js
        env:
          TZ: Asia/shanghai
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          YDZ_yuedongzuTOKEN: ${{ secrets.YDZ_yuedongzuTOKEN }}
          YDZ_CASH: ${{ secrets.YDZ_CASH }}
